/**
 * This file was automatically generated by GraphQL Nexus
 * Do not make changes to this file directly
 */

import * as Context from "./context"
import * as photon from "@generated/photon"



declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CollectionCreateInput: { // input type
    createdAt?: any | null; // DateTime
    date?: string | null; // String
    detail?: string | null; // String
    id?: string | null; // ID
    items?: NexusGenInputs['ItemCreateManyWithoutItemsInput'] | null; // ItemCreateManyWithoutItemsInput
    name: string; // String!
    owner: NexusGenInputs['UserCreateOneWithoutOwnerInput']; // UserCreateOneWithoutOwnerInput!
    section: NexusGenInputs['SectionCreateOneWithoutSectionInput']; // SectionCreateOneWithoutSectionInput!
    slug: string; // String!
  }
  CollectionCreateManyWithoutCollectionsInput: { // input type
    connect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null; // [CollectionWhereUniqueInput!]
    create?: NexusGenInputs['CollectionCreateWithoutSectionInput'][] | null; // [CollectionCreateWithoutSectionInput!]
  }
  CollectionCreateWithoutSectionInput: { // input type
    createdAt?: any | null; // DateTime
    date?: string | null; // String
    detail?: string | null; // String
    id?: string | null; // ID
    items?: NexusGenInputs['ItemCreateManyWithoutItemsInput'] | null; // ItemCreateManyWithoutItemsInput
    name: string; // String!
    owner: NexusGenInputs['UserCreateOneWithoutOwnerInput']; // UserCreateOneWithoutOwnerInput!
    slug: string; // String!
  }
  CollectionFilter: { // input type
    every?: NexusGenInputs['CollectionWhereInput'] | null; // CollectionWhereInput
    none?: NexusGenInputs['CollectionWhereInput'] | null; // CollectionWhereInput
    some?: NexusGenInputs['CollectionWhereInput'] | null; // CollectionWhereInput
  }
  CollectionWhereInput: { // input type
    AND?: NexusGenInputs['CollectionWhereInput'][] | null; // [CollectionWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    date?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    detail?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    items?: NexusGenInputs['ItemFilter'] | null; // ItemFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['CollectionWhereInput'][] | null; // [CollectionWhereInput!]
    OR?: NexusGenInputs['CollectionWhereInput'][] | null; // [CollectionWhereInput!]
    owner?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    section?: NexusGenInputs['SectionWhereInput'] | null; // SectionWhereInput
    slug?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  CollectionWhereUniqueInput: { // input type
    id?: string | null; // ID
    slug?: string | null; // String
  }
  DateTimeFilter: { // input type
    equals?: any | null; // DateTime
    gt?: any | null; // DateTime
    gte?: any | null; // DateTime
    in?: any[] | null; // [DateTime!]
    lt?: any | null; // DateTime
    lte?: any | null; // DateTime
    not?: any | null; // DateTime
    notIn?: any[] | null; // [DateTime!]
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: number | null; // Int
    notIn?: number[] | null; // [Int!]
  }
  ItemCreateManyWithoutItemsInput: { // input type
    connect?: NexusGenInputs['ItemWhereUniqueInput'][] | null; // [ItemWhereUniqueInput!]
    create?: NexusGenInputs['ItemCreateWithoutCollectionInput'][] | null; // [ItemCreateWithoutCollectionInput!]
  }
  ItemCreateWithoutCollectionInput: { // input type
    author?: string | null; // String
    comment?: string | null; // String
    createdAt?: any | null; // DateTime
    description?: string | null; // String
    id?: string | null; // ID
    imageUrl?: string | null; // String
    meta?: string | null; // String
    productUrl?: string | null; // String
    title: string; // String!
    type: NexusGenEnums['ItemType']; // ItemType!
    updatedAt?: any | null; // DateTime
  }
  ItemFilter: { // input type
    every?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    none?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    some?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
  }
  ItemWhereInput: { // input type
    AND?: NexusGenInputs['ItemWhereInput'][] | null; // [ItemWhereInput!]
    author?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    collection?: NexusGenInputs['CollectionWhereInput'] | null; // CollectionWhereInput
    comment?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    imageUrl?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    meta?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    NOT?: NexusGenInputs['ItemWhereInput'][] | null; // [ItemWhereInput!]
    OR?: NexusGenInputs['ItemWhereInput'][] | null; // [ItemWhereInput!]
    productUrl?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    type?: NexusGenEnums['ItemType'] | null; // ItemType
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  ItemWhereUniqueInput: { // input type
    id?: string | null; // ID
  }
  NullableStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: string | null; // String
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  ProfileCreateOneWithoutProfileInput: { // input type
    connect?: NexusGenInputs['ProfileWhereUniqueInput'] | null; // ProfileWhereUniqueInput
    create?: NexusGenInputs['ProfileCreateWithoutUsersInput'] | null; // ProfileCreateWithoutUsersInput
  }
  ProfileCreateWithoutUsersInput: { // input type
    github?: string | null; // String
    id?: string | null; // ID
    linkedin?: string | null; // String
    mail?: string | null; // String
    website?: string | null; // String
    youtube?: string | null; // String
  }
  ProfileWhereInput: { // input type
    AND?: NexusGenInputs['ProfileWhereInput'][] | null; // [ProfileWhereInput!]
    github?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    linkedin?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    mail?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    NOT?: NexusGenInputs['ProfileWhereInput'][] | null; // [ProfileWhereInput!]
    OR?: NexusGenInputs['ProfileWhereInput'][] | null; // [ProfileWhereInput!]
    users?: NexusGenInputs['UserFilter'] | null; // UserFilter
    website?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    youtube?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
  }
  ProfileWhereUniqueInput: { // input type
    id?: string | null; // ID
  }
  QueryCollectionsOrderByInput: { // input type
    date?: NexusGenEnums['OrderByArg'] | null; // OrderByArg
  }
  QueryCollectionsWhereInput: { // input type
    owner?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    section?: NexusGenInputs['SectionWhereInput'] | null; // SectionWhereInput
  }
  QuerySectionsWhereInput: { // input type
    owner?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
  }
  SectionCreateInput: { // input type
    collections?: NexusGenInputs['CollectionCreateManyWithoutCollectionsInput'] | null; // CollectionCreateManyWithoutCollectionsInput
    createdAt?: any | null; // DateTime
    id?: string | null; // ID
    index?: number | null; // Int
    name: string; // String!
    owner: NexusGenInputs['UserCreateOneWithoutOwnerInput']; // UserCreateOneWithoutOwnerInput!
    slug: string; // String!
  }
  SectionCreateManyWithoutSectionsInput: { // input type
    connect?: NexusGenInputs['SectionWhereUniqueInput'][] | null; // [SectionWhereUniqueInput!]
    create?: NexusGenInputs['SectionCreateWithoutOwnerInput'][] | null; // [SectionCreateWithoutOwnerInput!]
  }
  SectionCreateOneWithoutSectionInput: { // input type
    connect?: NexusGenInputs['SectionWhereUniqueInput'] | null; // SectionWhereUniqueInput
    create?: NexusGenInputs['SectionCreateWithoutCollectionsInput'] | null; // SectionCreateWithoutCollectionsInput
  }
  SectionCreateWithoutCollectionsInput: { // input type
    createdAt?: any | null; // DateTime
    id?: string | null; // ID
    index?: number | null; // Int
    name: string; // String!
    owner: NexusGenInputs['UserCreateOneWithoutOwnerInput']; // UserCreateOneWithoutOwnerInput!
    slug: string; // String!
  }
  SectionCreateWithoutOwnerInput: { // input type
    collections?: NexusGenInputs['CollectionCreateManyWithoutCollectionsInput'] | null; // CollectionCreateManyWithoutCollectionsInput
    createdAt?: any | null; // DateTime
    id?: string | null; // ID
    index?: number | null; // Int
    name: string; // String!
    slug: string; // String!
  }
  SectionFilter: { // input type
    every?: NexusGenInputs['SectionWhereInput'] | null; // SectionWhereInput
    none?: NexusGenInputs['SectionWhereInput'] | null; // SectionWhereInput
    some?: NexusGenInputs['SectionWhereInput'] | null; // SectionWhereInput
  }
  SectionWhereInput: { // input type
    AND?: NexusGenInputs['SectionWhereInput'][] | null; // [SectionWhereInput!]
    collections?: NexusGenInputs['CollectionFilter'] | null; // CollectionFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    index?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['SectionWhereInput'][] | null; // [SectionWhereInput!]
    OR?: NexusGenInputs['SectionWhereInput'][] | null; // [SectionWhereInput!]
    owner?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    slug?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  SectionWhereUniqueInput: { // input type
    id?: string | null; // ID
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: string | null; // String
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  UserCreateOneWithoutOwnerInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    create?: NexusGenInputs['UserCreateWithoutCollectionsInput'] | null; // UserCreateWithoutCollectionsInput
  }
  UserCreateWithoutCollectionsInput: { // input type
    biography: string; // String!
    createdAt?: any | null; // DateTime
    firstname: string; // String!
    id?: string | null; // ID
    label?: string | null; // String
    pictureUrl: string; // String!
    profile?: NexusGenInputs['ProfileCreateOneWithoutProfileInput'] | null; // ProfileCreateOneWithoutProfileInput
    sections?: NexusGenInputs['SectionCreateManyWithoutSectionsInput'] | null; // SectionCreateManyWithoutSectionsInput
    slug: string; // String!
  }
  UserFilter: { // input type
    every?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    none?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    some?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
  }
  UserWhereInput: { // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    biography?: NexusGenInputs['StringFilter'] | null; // StringFilter
    collections?: NexusGenInputs['CollectionFilter'] | null; // CollectionFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    firstname?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    label?: NexusGenInputs['NullableStringFilter'] | null; // NullableStringFilter
    NOT?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    pictureUrl?: NexusGenInputs['StringFilter'] | null; // StringFilter
    profile?: NexusGenInputs['ProfileWhereInput'] | null; // ProfileWhereInput
    sections?: NexusGenInputs['SectionFilter'] | null; // SectionFilter
    slug?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  UserWhereUniqueInput: { // input type
    id?: string | null; // ID
    slug?: string | null; // String
  }
}

export interface NexusGenEnums {
  ItemType: photon.ItemType
  OrderByArg: photon.OrderByArg
}

export interface NexusGenRootTypes {
  Collection: photon.Collection;
  Item: photon.Item;
  Mutation: {};
  Profile: photon.Profile;
  Query: {};
  Section: photon.Section;
  User: photon.User;
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  DateTime: any;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  CollectionCreateInput: NexusGenInputs['CollectionCreateInput'];
  CollectionCreateManyWithoutCollectionsInput: NexusGenInputs['CollectionCreateManyWithoutCollectionsInput'];
  CollectionCreateWithoutSectionInput: NexusGenInputs['CollectionCreateWithoutSectionInput'];
  CollectionFilter: NexusGenInputs['CollectionFilter'];
  CollectionWhereInput: NexusGenInputs['CollectionWhereInput'];
  CollectionWhereUniqueInput: NexusGenInputs['CollectionWhereUniqueInput'];
  DateTimeFilter: NexusGenInputs['DateTimeFilter'];
  IntFilter: NexusGenInputs['IntFilter'];
  ItemCreateManyWithoutItemsInput: NexusGenInputs['ItemCreateManyWithoutItemsInput'];
  ItemCreateWithoutCollectionInput: NexusGenInputs['ItemCreateWithoutCollectionInput'];
  ItemFilter: NexusGenInputs['ItemFilter'];
  ItemWhereInput: NexusGenInputs['ItemWhereInput'];
  ItemWhereUniqueInput: NexusGenInputs['ItemWhereUniqueInput'];
  NullableStringFilter: NexusGenInputs['NullableStringFilter'];
  ProfileCreateOneWithoutProfileInput: NexusGenInputs['ProfileCreateOneWithoutProfileInput'];
  ProfileCreateWithoutUsersInput: NexusGenInputs['ProfileCreateWithoutUsersInput'];
  ProfileWhereInput: NexusGenInputs['ProfileWhereInput'];
  ProfileWhereUniqueInput: NexusGenInputs['ProfileWhereUniqueInput'];
  QueryCollectionsOrderByInput: NexusGenInputs['QueryCollectionsOrderByInput'];
  QueryCollectionsWhereInput: NexusGenInputs['QueryCollectionsWhereInput'];
  QuerySectionsWhereInput: NexusGenInputs['QuerySectionsWhereInput'];
  SectionCreateInput: NexusGenInputs['SectionCreateInput'];
  SectionCreateManyWithoutSectionsInput: NexusGenInputs['SectionCreateManyWithoutSectionsInput'];
  SectionCreateOneWithoutSectionInput: NexusGenInputs['SectionCreateOneWithoutSectionInput'];
  SectionCreateWithoutCollectionsInput: NexusGenInputs['SectionCreateWithoutCollectionsInput'];
  SectionCreateWithoutOwnerInput: NexusGenInputs['SectionCreateWithoutOwnerInput'];
  SectionFilter: NexusGenInputs['SectionFilter'];
  SectionWhereInput: NexusGenInputs['SectionWhereInput'];
  SectionWhereUniqueInput: NexusGenInputs['SectionWhereUniqueInput'];
  StringFilter: NexusGenInputs['StringFilter'];
  UserCreateOneWithoutOwnerInput: NexusGenInputs['UserCreateOneWithoutOwnerInput'];
  UserCreateWithoutCollectionsInput: NexusGenInputs['UserCreateWithoutCollectionsInput'];
  UserFilter: NexusGenInputs['UserFilter'];
  UserWhereInput: NexusGenInputs['UserWhereInput'];
  UserWhereUniqueInput: NexusGenInputs['UserWhereUniqueInput'];
  ItemType: NexusGenEnums['ItemType'];
  OrderByArg: NexusGenEnums['OrderByArg'];
}

export interface NexusGenFieldTypes {
  Collection: { // field return type
    date: string | null; // String
    detail: string | null; // String
    id: string; // ID!
    items: NexusGenRootTypes['Item'][]; // [Item!]!
    name: string; // String!
    owner: NexusGenRootTypes['User']; // User!
    section: NexusGenRootTypes['Section']; // Section!
    slug: string; // String!
  }
  Item: { // field return type
    author: string | null; // String
    comment: string | null; // String
    description: string | null; // String
    id: string; // ID!
    imageUrl: string | null; // String
    meta: string | null; // String
    productUrl: string | null; // String
    title: string; // String!
    type: NexusGenEnums['ItemType']; // ItemType!
  }
  Mutation: { // field return type
    createItem: NexusGenRootTypes['Item']; // Item!
    createOneCollection: NexusGenRootTypes['Collection']; // Collection!
    createOneSection: NexusGenRootTypes['Section']; // Section!
  }
  Profile: { // field return type
    linkedin: string | null; // String
    mail: string | null; // String
    website: string | null; // String
    youtube: string | null; // String
  }
  Query: { // field return type
    collection: NexusGenRootTypes['Collection'] | null; // Collection
    collections: NexusGenRootTypes['Collection'][]; // [Collection!]!
    section: NexusGenRootTypes['Section'] | null; // Section
    sections: NexusGenRootTypes['Section'][]; // [Section!]!
    user: NexusGenRootTypes['User'] | null; // User
  }
  Section: { // field return type
    collections: NexusGenRootTypes['Collection'][]; // [Collection!]!
    id: string; // ID!
    index: number; // Int!
    name: string; // String!
    slug: string; // String!
  }
  User: { // field return type
    biography: string; // String!
    firstname: string; // String!
    id: string; // ID!
    label: string | null; // String
    pictureUrl: string; // String!
    profile: NexusGenRootTypes['Profile'] | null; // Profile
    sections: NexusGenRootTypes['Section'][]; // [Section!]!
    slug: string; // String!
  }
}

export interface NexusGenArgTypes {
  Collection: {
    items: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  Mutation: {
    createItem: { // args
      collectionId: string; // String!
      overridedTitle?: string | null; // String
      url: string; // String!
    }
    createOneCollection: { // args
      data: NexusGenInputs['CollectionCreateInput']; // CollectionCreateInput!
    }
    createOneSection: { // args
      data: NexusGenInputs['SectionCreateInput']; // SectionCreateInput!
    }
  }
  Query: {
    collection: { // args
      where: NexusGenInputs['CollectionWhereUniqueInput']; // CollectionWhereUniqueInput!
    }
    collections: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['QueryCollectionsOrderByInput'] | null; // QueryCollectionsOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['QueryCollectionsWhereInput'] | null; // QueryCollectionsWhereInput
    }
    section: { // args
      where: NexusGenInputs['SectionWhereUniqueInput']; // SectionWhereUniqueInput!
    }
    sections: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
      where?: NexusGenInputs['QuerySectionsWhereInput'] | null; // QuerySectionsWhereInput
    }
    user: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
  Section: {
    collections: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  User: {
    sections: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Collection" | "Item" | "Mutation" | "Profile" | "Query" | "Section" | "User";

export type NexusGenInputNames = "CollectionCreateInput" | "CollectionCreateManyWithoutCollectionsInput" | "CollectionCreateWithoutSectionInput" | "CollectionFilter" | "CollectionWhereInput" | "CollectionWhereUniqueInput" | "DateTimeFilter" | "IntFilter" | "ItemCreateManyWithoutItemsInput" | "ItemCreateWithoutCollectionInput" | "ItemFilter" | "ItemWhereInput" | "ItemWhereUniqueInput" | "NullableStringFilter" | "ProfileCreateOneWithoutProfileInput" | "ProfileCreateWithoutUsersInput" | "ProfileWhereInput" | "ProfileWhereUniqueInput" | "QueryCollectionsOrderByInput" | "QueryCollectionsWhereInput" | "QuerySectionsWhereInput" | "SectionCreateInput" | "SectionCreateManyWithoutSectionsInput" | "SectionCreateOneWithoutSectionInput" | "SectionCreateWithoutCollectionsInput" | "SectionCreateWithoutOwnerInput" | "SectionFilter" | "SectionWhereInput" | "SectionWhereUniqueInput" | "StringFilter" | "UserCreateOneWithoutOwnerInput" | "UserCreateWithoutCollectionsInput" | "UserFilter" | "UserWhereInput" | "UserWhereUniqueInput";

export type NexusGenEnumNames = "ItemType" | "OrderByArg";

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "DateTime" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}